# NumPy Practice Questions — Session 15

## Topics Covered

- `np.sort()`
- `np.append()`
- `np.concatenate()`
- `np.unique()`
- `np.expand_dims()`
- `np.where()`
- `np.argmax()`
- `np.argmin()`
- `np.cumsum()`
- `np.cumprod()`
- `np.percentile()`
- `np.histogram()`
- `np.corrcoef()`
- `np.isin()`
- `np.flip()`
- `np.put()`
- `np.delete()`
- NumPy Set Functions
- `np.clip()`

> **Instructions**
>
> - Solve all questions using **NumPy only** unless specified otherwise.
> - Do **not** use Python built-in alternatives if a NumPy function exists.
> - Write clean, readable code.
> - Print the output after every task.

# Question 1 — Student Marks Analyzer

## Problem Statement

Create the following NumPy array:

```python
marks = np.array([78, 45, 91, 62, 45, 99, 78, 35, 91, 55])
```

Perform the following tasks:

- Sort the marks in ascending order.
- Find all unique marks.
- Find the index of the highest mark.
- Find the index of the lowest mark.
- Find all indices where marks are greater than 75.

### Example Output

```text
Sorted Marks:
[35 45 45 55 62 78 78 91 91 99]

Unique Marks:
[35 45 55 62 78 91 99]

Highest Mark Index:
5

Lowest Mark Index:
7

Indices of Marks > 75:
[0 2 5 6 8]
```

In [1]:
import numpy as np

marks = np.array([78, 45, 91, 62, 45, 99, 78, 35, 91, 55])

sorted_marks = np.sort(marks)
unique_marks = np.unique(marks)
highest_index = np.argmax(marks)
lowest_index = np.argmin(marks)
greater_than_75_index = np.where(marks > 75)[0]

print("Sorted Marks:", sorted_marks)
print("Unique Marks:", unique_marks)
print("Highest Mark Index:", highest_index)
print("Lowest Mark Index:", lowest_index)
print("Indices of Marks > 75:", greater_than_75_index)

Sorted Marks: [35 45 45 55 62 78 78 91 91 99]
Unique Marks: [35 45 55 62 78 91 99]
Highest Mark Index: 5
Lowest Mark Index: 7
Indices of Marks > 75: [0 2 5 6 8]


# Question 2 — Product Sales Report

## Problem Statement

Create the following arrays:

```python
store_a = np.array([120, 150, 180, 210])
store_b = np.array([100, 170, 200, 240])
```

Perform the following tasks:

- Combine both arrays vertically.
- Combine both arrays horizontally.
- Calculate the cumulative sum of Store A.
- Calculate the cumulative product of Store A.
- Find the 50th percentile of Store A.

### Example Output

```text
Vertical Combination:
[[120 150 180 210]
 [100 170 200 240]]

Horizontal Combination:
[120 150 180 210 100 170 200 240]

Cumulative Sum:
[120 270 450 660]

Cumulative Product:
[120 18000 3240000 680400000]

50th Percentile:
165.0
```


In [2]:
store_a = np.array([120, 150, 180, 210])
store_b = np.array([100, 170, 200, 240])

vertical_comb = np.concatenate(([store_a], [store_b]), axis=0)
horizontal_comb = np.concatenate((store_a, store_b))
cum_sum = np.cumsum(store_a)
cum_prod = np.cumprod(store_a)
percentile_50 = np.percentile(store_a, 50)

print("Vertical Combination:\n", vertical_comb)
print("Horizontal Combination:", horizontal_comb)
print("Cumulative Sum:", cum_sum)
print("Cumulative Product:", cum_prod)
print("50th Percentile:", percentile_50)

Vertical Combination:
 [[120 150 180 210]
 [100 170 200 240]]
Horizontal Combination: [120 150 180 210 100 170 200 240]
Cumulative Sum: [120 270 450 660]
Cumulative Product: [      120     18000   3240000 680400000]
50th Percentile: 165.0


# Question 3 — Employee Database Update

## Problem Statement

Create the following array:

```python
emp_ids = np.array([101, 102, 103, 104, 105, 106])
```

Perform the following tasks:

- Replace the values at index `1` and `4` with new employee IDs.
- Delete the employee at index `3`.
- Append a new employee ID at the end.
- Reverse the final array.

### Example Output

```text
Updated IDs:
[101 202 103 104 505 106]

After Deletion:
[101 202 103 505 106]

After Appending:
[101 202 103 505 106 999]

After Flipping:
[999 106 505 103 202 101]
```

In [3]:
emp_ids = np.array([101, 102, 103, 104, 105, 106])

np.put(emp_ids, [1, 4], [202, 505])
print("Updated IDs:", emp_ids)

after_deletion = np.delete(emp_ids, 3)
print("After Deletion:", after_deletion)

after_appending = np.append(after_deletion, 999)
print("After Appending:", after_appending)

after_flipping = np.flip(after_appending)
print("After Flipping:", after_flipping)

Updated IDs: [101 202 103 104 505 106]
After Deletion: [101 202 103 505 106]
After Appending: [101 202 103 505 106 999]
After Flipping: [999 106 505 103 202 101]


# Question 4 — Customer Purchase Analysis

## Problem Statement

Create the following array:

```python
purchases = np.array([101, 102, 103, 101, 105, 106, 102, 103, 108, 109])
```

Also create:

```python
search_items = np.array([101, 104, 108, 110])
```

Perform the following tasks:

- Find all unique product IDs.
- Check whether each value in `search_items` exists in `purchases`.
- Replace every product ID greater than `105` with `0`.
- Generate a histogram using **5 bins**.

### Example Output

```text
Unique Products:
[101 102 103 105 106 108 109]

Exists:
[ True False True False]

Modified Array:
[101 102 103 101 105   0 102 103   0   0]

Histogram:
Counts: [...]
Bins: [...]
```


In [4]:
purchases = np.array([101, 102, 103, 101, 105, 106, 102, 103, 108, 109])
search_items = np.array([101, 104, 108, 110])

unique_purchases = np.unique(purchases)
exists = np.isin(search_items, purchases)
modified_array = np.where(purchases > 105, 0, purchases)
counts, bins = np.histogram(purchases, bins=5)

print("Unique Products:", unique_purchases)
print("Exists:", exists)
print("Modified Array:", modified_array)
print("Histogram:")
print("  Counts:", counts)
print("  Bins:", bins)

Unique Products: [101 102 103 105 106 108 109]
Exists: [ True False  True False]
Modified Array: [101 102 103 101 105   0 102 103   0   0]
Histogram:
  Counts: [4 2 1 1 2]
  Bins: [101.  102.6 104.2 105.8 107.4 109. ]


# Question 5 — Data Science Mini Challenge

## Problem Statement

Create the following arrays:

```python
study_hours = np.array([1, 2, 3, 4, 5, 6, 7, 8])

scores = np.array([35, 40, 50, 60, 68, 75, 82, 90])
```

Perform the following tasks:

- Find the correlation coefficient between `study_hours` and `scores`.
- Convert `study_hours` into a column vector.
- Clip all scores so that values remain between `40` and `80`.
- Find the indices where scores are greater than or equal to `70`.

### Example Output

```text
Correlation Matrix:
[[1.0 ...]
 [... 1.0]]

Expanded Shape:
(8, 1)

Clipped Scores:
[40 40 50 60 68 75 80 80]

Indices >= 70:
[5 6 7]
```


In [5]:
study_hours = np.array([1, 2, 3, 4, 5, 6, 7, 8])
scores = np.array([35, 40, 50, 60, 68, 75, 82, 90])

corr_matrix = np.corrcoef(study_hours, scores)
expanded_shape = np.expand_dims(study_hours, axis=1).shape
clipped_scores = np.clip(scores, 40, 80)
indices_70 = np.where(scores >= 70)[0]

print("Correlation Matrix:\n", corr_matrix)
print("Expanded Shape:", expanded_shape)
print("Clipped Scores:", clipped_scores)
print("Indices >= 70:", indices_70)

Correlation Matrix:
 [[1.         0.99785328]
 [0.99785328 1.        ]]
Expanded Shape: (8, 1)
Clipped Scores: [40 40 50 60 68 75 80 80]
Indices >= 70: [5 6 7]


# Conclusion

After completing these practice questions, you should be comfortable with:

- ✅ Sorting arrays
- ✅ Appending and deleting elements
- ✅ Concatenating arrays
- ✅ Finding unique values
- ✅ Expanding array dimensions
- ✅ Conditional filtering using `np.where()`
- ✅ Finding maximum and minimum indices
- ✅ Cumulative sum and cumulative product
- ✅ Percentile calculations
- ✅ Histogram generation
- ✅ Correlation coefficient
- ✅ Membership testing with `np.isin()`
- ✅ Reversing arrays
- ✅ Updating values using `np.put()`
- ✅ NumPy set operations
- ✅ Clipping values within a range

These functions are frequently used in **Data Analysis**, **Machine Learning**, **Deep Learning**, and **Scientific Computing**, making them essential tools for every NumPy learner.