# NumPy Practice Questions - Session 1

## Topics Covered

- import numpy as np
- np.array()
- np.arange()
- reshape()
- np.ones()
- np.zeros()
- np.random.random()
- np.linspace()
- np.identity()
- Array Attributes
  - ndim
  - shape
  - size
  - itemsize
  - dtype
- astype()
- Scalar Operations
- Vector Operations
- Basic NumPy Functions
  - max()
  - min()
  - sum()
  - prod()

---

> ## Instructions
>
> - Solve all questions in Jupyter Notebook.
> - Do **not** search for solutions.
> - Use meaningful variable names.
> - Print the output after every step.
> - Try solving each question without referring to your notes.


# Question 1 — NumPy Array Creation

Create the following arrays:

1. A 1D NumPy array containing numbers from **10 to 15**.
2. A **3 × 4** array containing numbers from **1 to 12** using `np.arange()` and `reshape()`.
3. A **3 × 3 Identity Matrix**.

Print all three arrays.

### Example Output

```text
Array 1
[10 11 12 13 14 15]

Array 2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Identity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```


In [1]:
import numpy as np

a1 = np.arange(10,16).reshape(1,6)
a2 = np.arange(1,13).reshape(3,4)
a3 = np.identity(3)

print("Array 1")
print(a1,"\n")
print("Array 2")
print(a2,"\n")
print("Identity Matrix")
print(a3)

Array 1
[[10 11 12 13 14 15]] 

Array 2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Identity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Question 2 — Array Attributes

Create a NumPy array having **4 rows and 5 columns**.

Print the following:

- Number of Dimensions
- Shape
- Total Number of Elements
- Item Size
- Data Type

### Example Output

```text
Number of Dimensions : 2
Shape                : (4, 5)
Total Elements       : 20
Item Size            : 8
Data Type            : int64
```

In [2]:
a = np.arange(1,21).reshape(4,5)

print(f"Number of Dimension : {a.ndim}")
print(f"Shape               : {a.shape}")
print(f"Total Elements      : {a.size}")
print(f"Item Size           : {a.itemsize}")
print(f"Data Type           : {a.dtype}")

Number of Dimension : 2
Shape               : (4, 5)
Total Elements      : 20
Item Size           : 8
Data Type           : int64


# Question 3 — Data Type Conversion

Create a NumPy array containing numbers from **1 to 10**.

Convert the array into:

- Float
- Boolean

Print:

- Original Array
- Converted Arrays
- Data Types

### Example Output

```text
Original Array
[1 2 3 4 5 6 7 8 9 10]

Original dtype
int64

Float Array
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

Float dtype
float64

Boolean Array
[ True  True  True  True  True  True  True  True  True  True]

Boolean dtype
bool
```

In [3]:
a = np.arange(1,11)
print("Original Array")
print(a,"\n")
print("Original dtype")
print(a.dtype,"\n")
a.astype(float)
print("Float Array")
print(a,"\n")
print("Float dtype")
print(a.dtype,"\n")
a.astype(bool)
print("Boolean Array")
print(a,"\n")
print("Boolean dtype")
print(a.dtype)

Original Array
[ 1  2  3  4  5  6  7  8  9 10] 

Original dtype
int64 

Float Array
[ 1  2  3  4  5  6  7  8  9 10] 

Float dtype
int64 

Boolean Array
[ 1  2  3  4  5  6  7  8  9 10] 

Boolean dtype
int64


# Question 4 — Array Initialization

Create the following arrays:

- A **4 × 4** array filled with zeros.
- A **4 × 4** array filled with ones.
- A **3 × 3** array containing random values.
- A **10-element** array between **0 and 100** using `np.linspace()`.

Print every array.

### Example Output

```text
Zeros Array

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Random Array

[[0.45 0.82 0.19]
 [0.67 0.11 0.56]
 [0.39 0.74 0.98]]

Linspace Array

[  0.          11.11111111  22.22222222  33.33333333
  44.44444444  55.55555556  66.66666667  77.77777778
  88.88888889 100.        ]
```

In [4]:
a1 = np.zeros((4,4))
a2 = np.ones((4,4))
a3 = np.round(np.random.rand(3,3),2)
a4 = np.linspace(0,100,10)

print("Zeros Array\n")
print(a1,"\n")
print("Ones Array\n")
print(a2,"\n")
print("Random Array\n")
print(a3,"\n")
print("Linspace Array\n")
print(a4)

Zeros Array

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Ones Array

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Random Array

[[0.1  0.94 0.38]
 [0.89 0.44 0.97]
 [0.54 0.92 0.41]] 

Linspace Array

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


# Question 5 — Array Operations

Create two **3 × 3** NumPy arrays.

Perform the following operations:

- Addition
- Subtraction
- Multiplication
- Division
- Maximum
- Minimum
- Sum
- Product

Print every result separately.

### Example Input

```text
Array A

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array B

[[9 8 7]
 [6 5 4]
 [3 2 1]]
```

### Example Output

```text
Addition

[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Multiplication

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Division

[[0.11 0.25 0.43]
 [0.67 1.00 1.50]
 [2.33 4.00 9.00]]

Maximum : 9

Minimum : 1

Sum : 45

Product : 362880
```

In [5]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(9,0,-1).reshape(3,3)

print("Addition\n")
print(a1 + a2,"\n")

print("Subtraction\n")
print(a1 - a2,"\n")

print("Multiplication\n")
print(a1 * a2,"\n")

print("Division\n")
print(np.round(a1 / a2, 2),"\n")

print(f"Maximum : {np.max(a1)}\n")
print(f"Minimum : {np.min(a1)}\n")
print(f"Sum : {np.sum(a1)}\n")
print(f"Product : {np.prod(a1)}")

Addition

[[10 10 10]
 [10 10 10]
 [10 10 10]] 

Subtraction

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]] 

Multiplication

[[ 9 16 21]
 [24 25 24]
 [21 16  9]] 

Division

[[0.11 0.25 0.43]
 [0.67 1.   1.5 ]
 [2.33 4.   9.  ]] 

Maximum : 9

Minimum : 1

Sum : 45

Product : 362880


# Conclusion

🎉 Congratulations! You have completed **NumPy Practice Set – Session 1**.

If you solved all the questions successfully, you should now be comfortable with:

- ✅ Creating NumPy arrays
- ✅ Using `np.array()`
- ✅ Using `np.arange()` with `reshape()`
- ✅ Creating arrays using `ones()`, `zeros()`, `random()`, `linspace()`, and `identity()`
- ✅ Understanding array attributes (`ndim`, `shape`, `size`, `itemsize`, `dtype`)
- ✅ Converting data types using `astype()`
- ✅ Performing scalar and vector operations
- ✅ Using common NumPy functions (`max()`, `min()`, `sum()`, `prod()`)