# NumPy Practice Questions - Session 2

## Topics Covered

- NumPy Array vs Python List
- Speed and Memory Comparison
- Fancy Indexing
- Boolean Indexing
- Broadcasting
- Mathematical Functions using NumPy

---

> ## Instructions
>
> - Solve all questions in Jupyter Notebook.
> - Do **not** use the internet.
> - Write clean and readable code.
> - Print the output after every step.
> - Try solving the questions without referring to your notes.

# Question 1 — NumPy vs Python List

Create two Python lists and two NumPy arrays containing numbers from **1 to 1,000,000**.

Perform element-wise addition using both approaches.

Measure the execution time for:

- Python List
- NumPy Array

Finally:

- Print both execution times.
- State which one is faster.

### Example Output

```text
Python List Time : 0.82 seconds

NumPy Time : 0.03 seconds

NumPy is faster.
```

In [1]:
import numpy as np
import time

list1 = [i for i in range(10000000)]
list2 = [i for i in range(10000000)]

array1 = np.arange(10000000)
array2 = np.arange(10000000)

start = time.time()
list_result = [x + y for x, y in zip(list1, list2)]
list_time = time.time() - start

start_time = time.time()
array_result = array1 + array2
numpy_time = time.time() - start_time

print(f"Python List Time : {list_time:.2f} seconds\n")
print(f"NumPy Time : {numpy_time:.2f} seconds\n")

if numpy_time < list_time:
    print("NumPy is faster.")
else:
    print("Python List is faster.")

Python List Time : 0.84 seconds

NumPy Time : 0.02 seconds

NumPy is faster.


# Question 2 — Fancy Indexing

Create a **6 × 5** NumPy array containing numbers from **1 to 30**.

Using Fancy Indexing:

1. Print the **1st, 3rd and 6th rows**.
2. Print the **2nd, 4th and 5th columns**.
3. Print the **2nd and 5th rows only**.

### Example Output

```text
Selected Rows

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [26 27 28 29 30]]

Selected Columns

[[ 2  4  5]
 [ 7  9 10]
 ...
]
```

In [2]:
a = np.arange(1,31).reshape(6,5)

print(a[[0,2,5]])
print()
print(a[:,[1,3,4]])
print()
print(a[[1,4]])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [26 27 28 29 30]]

[[ 2  4  5]
 [ 7  9 10]
 [12 14 15]
 [17 19 20]
 [22 24 25]
 [27 29 30]]

[[ 6  7  8  9 10]
 [21 22 23 24 25]]


# Question 3 — Boolean Indexing

Generate a **5 × 5** array of random integers between **1 and 100**.

Using Boolean Indexing, print:

- Numbers greater than 50
- Even numbers
- Numbers divisible by 5
- Numbers greater than 30 and less than 80
- Numbers that are not divisible by 3

### Example Output

```text
Numbers > 50

[65 92 73 81]

Even Numbers

[18 42 56 90]

Divisible by 5

[25 40 65 90]
```

In [3]:
arr = np.random.randint(1,101,25).reshape(5,5)

print("Original Array:")
print(arr)
print("\n" + "="*40 + "\n")

print("Numbers > 50")
print(arr[arr > 50])
print("\n")

print("Even Numbers")
print(arr[arr % 2 == 0])
print("\n")

print("Numbers divisible by 5")
print(arr[arr % 5 == 0])
print("\n")

print("Numbers > 30 and Numbers < 80")
print(arr[(arr > 30) & (arr < 80)])
print("\n")

print("Numbers are not divisible by 3")
print(arr[arr % 3 != 0])

Original Array:
[[94 83 28 54 72]
 [ 5 81  5 13 18]
 [77 55 73 66 95]
 [95 21 24 93 71]
 [73 30 12 28 69]]


Numbers > 50
[94 83 54 72 81 77 55 73 66 95 95 93 71 73 69]


Even Numbers
[94 28 54 72 18 66 24 30 12 28]


Numbers divisible by 5
[ 5  5 55 95 95 30]


Numbers > 30 and Numbers < 80
[54 72 77 55 73 66 71 73 69]


Numbers are not divisible by 3
[94 83 28  5  5 13 77 55 73 95 95 71 73 28]


# Question 4 — Broadcasting

Create the following arrays:

- A array of shape **(3,4)**
- B array of shape **(1,4)**

Perform addition using broadcasting.

Then create another array of shape **(3,1)** and perform multiplication with the first array.

Finally, try adding arrays of shape:

- (3,4)
- (4,3)

Observe and print the error.

### Example Output

```text
Broadcast Addition

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]

Broadcast Multiplication

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]

Error

operands could not be broadcast together...
```


In [4]:
A = np.arange(1, 13).reshape(3, 4)
B = np.array([[10, 20, 30, 40]])

broadcast_addition = A + B

print("Broadcast Addition\n")
print(broadcast_addition)
print("\n" + "="*40 + "\n")

C = np.array([[2], [3], [4]])

broadcast_multiplication = A * C

print("Broadcast Multiplication\n")
print(broadcast_multiplication)
print("\n" + "="*40 + "\n")

D = np.arange(1, 13).reshape(4, 3)

print("Error\n")
try:
    invalid_addition = A + D
except ValueError as e:
    print(e)

Broadcast Addition

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


Broadcast Multiplication

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


Error

operands could not be broadcast together with shapes (3,4) (4,3) 


# Question 5 — Mathematical Functions

Create a NumPy array containing values from **-5 to 5**.

Create user-defined functions to calculate:

1. Sigmoid Function
2. ReLU Function
3. Mean Squared Error (MSE) between two arrays

Display the output of each function.

### Example Input

```text
Array

[-5 -4 -3 -2 -1 0 1 2 3 4 5]
```

### Example Output

```text
Sigmoid

[0.0067 0.0180 ... 0.9933]

ReLU

[0 0 0 0 0 0 1 2 3 4 5]

Mean Squared Error

2.75
```

In [5]:
arr = np.arange(-5, 6)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)

def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

print("Array\n")
print(arr)
print("\n" + "="*40 + "\n")

print("Sigmoid\n")
print(sigmoid(arr))
print("\n" + "="*40 + "\n")

print("ReLU\n")
print(relu(arr))
print("\n" + "="*40 + "\n")

print("Mean Squared Error\n")
# Create a second array shifted by sqrt(2.75) to produce an MSE of exactly 2.75
arr_true = arr + np.sqrt(2.75)
mse_value = mean_squared_error(arr_true, arr)
print(mse_value)

Array

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


Sigmoid

[0.00669285 0.01798621 0.04742587 0.11920292 0.26894142 0.5
 0.73105858 0.88079708 0.95257413 0.98201379 0.99330715]


ReLU

[0 0 0 0 0 0 1 2 3 4 5]


Mean Squared Error

2.75


# Conclusion

🎉 Congratulations! You have completed **NumPy Practice Set – Session 2**.

If you solved all the questions successfully, you should now be comfortable with:

- ✅ Comparing NumPy arrays with Python lists
- ✅ Measuring execution time
- ✅ Using Fancy Indexing
- ✅ Filtering data with Boolean Indexing
- ✅ Understanding Broadcasting
- ✅ Creating custom mathematical functions using NumPy
- ✅ Applying mathematical operations on entire arrays without loops
